name: Daily Run

on: [push] # TODO - change to schedule once its working

jobs:

  test:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 5
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: 3.*
    - name: Install the package
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]
    - name: Run Unit Tests
      run: |
        python -m unittest2 discover
    - name: Run Automated Tests
      run: |
        robot tests/integration_tests/test_suites/
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ${{ matrix.os }}_log.html
        path: log.html
        retention-days: 7