name: Release to PyPI

on:
  release:
    types: [published]

jobs:
  release:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Tools
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Build Package
      run: |
        python -m build
    - name: Publish to PyPi
      uses: pypa/gh-action-pypi-publish@v1.4.1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}
