name: Split Machine Test

on: [push, pull_request]

jobs:
  split-box-test:
    runs-on: ubuntu-latest
    services:
      rfagent:
        image: chrisbrookes93/appservicecontainer:3.8-slim-buster-v0.0.1
        env:
          GIT_URL: git://github.com/${{ github.repository }}.git
          GIT_COMMIT_HASH: ${{ github.sha }}
          APP_LAUNCH_CMDLINE: rfagent -p 1471
        ports:
          - 1471:1471

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install the package
        run: |
          pip install .
      # We need to give the service time to checkout, install and run the rfagent
      - name: Wait for rfagent service to start
        uses: nick-invision/retry@v2
        with:
          max_attempts: 5
          timeout_seconds: 15
          command: curl http://0.0.0.0:1471
      - name: Execute a remote run
        run: |
          rfremoterun 127.0.0.1 tests/unit_tests/rf_client_test_resources
      - name: Dump docker logs on failure
        if: failure()
        uses: jwalton/gh-docker-logs@v1
