name: CI

on: [push, pull_request]

jobs:

  split-box-test:

    runs-on: ubuntu-latest

    services:
      rfagent:
        image: chrisbrookes93/appservicecontainer:3.8-slim-buster-v0.0.1
        env:
          GIT_URL: git://github.com/chrisBrookes93/robotframework-remoterunner.git
          GIT_COMMIT_HASH: $GITHUB_SHA
          APP_LAUNCH_CMDLINE: rfagent -p 1471
        # Set health checks to wait until the rfagent is running
        options: >-
          --health-cmd curl http://0.0.0.0:1471
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 1471:1471

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Execute a remote run
        run: |
          rfremoterun 127.0.0.1 /tests/unit_tests/rf_client_test_resources
