name: CI

on: [push, pull_request]

jobs:

  split-box-test:

    runs-on: ubuntu-latest

    services:
      rfagent:
        image: chrisbrookes93/appservicecontainer:3.8-slim-buster-v0.0.1
        env:
          GIT_URL: git://github.com/chrisBrookes93/robotframework-remoterunner.git
          GIT_COMMIT_HASH: $GITHUB_SHA
          APP_LAUNCH_CMDLINE: rfagent -p 1471
        ports:
          - 1471:1471

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install the package
        run: |
          pip install .
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.2
        with:
          url: http://0.0.0.0:1471
          max-attempts: 15
          retry-delay: 5s
      - name: Execute a remote run
        run: |
          rfremoterun 127.0.0.1 tests/unit_tests/rf_client_test_resources
