name: Unit & Integration Tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [2.7, 3.7, 3.9]
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run Tox
      run: tox -e py
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ${{ matrix.os }}_py${{ matrix.python-version }}_log.html
        path: .tox/py_log.html
        retention-days: 7
