name: CI

on: [push, pull_request]

jobs:

  tox-tests:
    name: Tox Tests - ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 5
    strategy:
      matrix:
        include:
          - {name: Linux,     python-version: 3.9, os: ubuntu-latest,   tox: py}
          - {name: Windows,   python-version: 3.9, os: windows-latest,  tox: py}
          - {name: Mac,       python-version: 3.9, os: macos-latest,    tox: py}
          - {name: Py2.7,     python-version: 2.7, os: ubuntu-latest,   tox: py}
          - {name: Py3.6,     python-version: 3.6, os: ubuntu-latest,   tox: py}
          - {name: Py3.7,     python-version: 3.7, os: ubuntu-latest,   tox: py}
          - {name: Py3.8,     python-version: 3.8, os: ubuntu-latest,   tox: py}
          - {name: Py3.9,     python-version: 3.9, os: ubuntu-latest,   tox: py}
          - {name: Py3.x,     python-version: 3.x, os: ubuntu-latest,   tox: py}
          - {name: RF-3.1.1,  python-version: 3.9, os: ubuntu-latest,   tox: "py-robotframework{311}"}
          - {name: RF-3.2,    python-version: 3.9, os: ubuntu-latest,   tox: "py-robotframework{32}"}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox
    - name: Run Tox
      run: tox -e ${{ matrix.tox }}
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: ${{ matrix.os }}_py${{ matrix.python-version }}_log.html
        path: .tox/py_log.html
        retention-days: 7

  split-box-test:
    name: Docker Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Build Package
        run: |
          pip install build
          python -m build . -w
      - name: Launch containers
        working-directory: ./tests/docker
        run: docker-compose up --exit-code-from rf-remoterunner

  code-cov:
    name: Code Coverage
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev,codecov]
    - name: Run Pylint
      run: pylint rfremoterunner tests --fail-under 8.5
    - name: Run Code Coverage
      run: |
        pytest --cov=rfremoterunner --cov-fail-under=75