name: Split Machine Test

on: [push]

jobs:
  minimalist-split-box-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Build Package
        run: |
          pip install build
          python -m build . -w
      - name: Launch containers
        working-directory: ./tests/docker
        run: docker-compose up --exit-code-from rf-remoterunner
