name: CI
on: [push, pull_request]



jobs:


  split-box-test:
    name: Split-Box Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Build Package
        run: |
          pip install build
          python -m build . -w
      - name: Install locally from whl
        run: pip install ./dist/*
      - name: Launch rfagent container
        run: docker run -d -p 1471:1471 -v $(pwd)/dist:/package python:3.8-slim-buster /bin/bash -c "pip install /package/* && rfagent"
      - name: Run rf-remoterun
        run: rfremoterun 0.0.0.0:1471 tests/unit_tests/rf_client_test_resources/TS1.robot
